In [18]:
#data load

import pandas as pd

df = pd.read_excel("sales_raw_500.xlsx")

In [19]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
515      1389 2024-02-12    Vikas  North   Laptop  17924  12145
516      1496 2023-04-24    Kiran  North  Printer  23434  16388
517      1031 2023-02-19    Vikas   East  Printer  58883  43579
518      1317 2023-07-05     Aman  North   Laptop  76781  66865
519      1409 2024-01-16    Pooja  North  Monitor  19969  13586

[520 rows x 7 columns]

In [20]:
#Remove duplicacy

df = df.drop_duplicates()

In [21]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
498      1499        NaT    Pooja   West   Mobile  59266  44326
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[500 rows x 7 columns]

In [22]:
#Fixing date column

df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')

C:\Users\suman\AppData\Local\Temp\ipykernel_11864\3787364510.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')

In [23]:
df = df.dropna(subset=['Order_Date'])

In [24]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
494      1495 2023-10-18    Rahul  South  Monitor  46709  40931
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[482 rows x 7 columns]

In [25]:
#Create new column "Profit", "Month" and "Year"

df['Profit'] = df['Sales'] - df['Cost']
df['Year'] = df['Order_Date'].dt.year
df['Month'] = df['Order_Date'].dt.month

C:\Users\suman\AppData\Local\Temp\ipykernel_11864\3130810997.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Profit'] = df['Sales'] - df['Cost']
C:\Users\suman\AppData\Local\Temp\ipykernel_11864\3130810997.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Year'] = df['Order_Date'].dt.year
C:\Users\suman\AppData\Local\Temp\ipykernel_11864\3130810997.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Month'] = df['Order_Date'].dt.month

In [26]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...
494,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,2023,10
495,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,2023,4
496,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,2023,6
497,1498,2023-05-08,Aman,East,Tablet,19160,15636,3524,2023,5
499,1500,2023-10-07,Vikas,North,Printer,34567,22426,12141,2023,10

In [32]:
#Excel to CSV, CSV File without indexing column

df.to_csv('sales_cleaned.csv', index = False)

In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
df = pd.read_csv('sales_cleaned.csv')

In [4]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,1001,13-01-2023,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,07-10-2023,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,05-11-2023,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,19-02-2024,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,26-01-2024,Anjali,North,Laptop,54797,34468,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...
477,1495,18-10-2023,Rahul,South,Monitor,46709,40931,5778,2023,10
478,1496,24-04-2023,Kiran,North,Printer,23434,16388,7046,2023,4
479,1497,27-06-2023,Anjali,South,Laptop,49007,35970,13037,2023,6
480,1498,08-05-2023,Aman,East,Tablet,19160,15636,3524,2023,5
481,1500,07-10-2023,Vikas,North,Printer,34567,22426,12141,2023,10

In [6]:
engine = create_engine('mysql+pymysql://root:AllySQL@localhost:3306/salesdb')

In [7]:
df.to_sql(name='sales_data' , con=engine , if_exists = 'replace' , index = False)

482